//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for creation-method.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="creation-method">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="API"/>
 *     &lt;enumeration value="website"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "creation-method")
@XmlEnum
public enum CreationMethod {

	/**
	 * The ORCID Record was created using the ORCID Member API.
	 * 
	 * 
	 */
	API("API"),

	/**
	 * The ORCID Record was created manually by the reseracher or contributor
	 * using the ORCID web user interface.
	 * 
	 * 
	 */
	@XmlEnumValue("website")
	WEBSITE("website");
	private final String value;

	CreationMethod(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static CreationMethod fromValue(String v) {
		for (CreationMethod c : CreationMethod.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
