//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}agency-orcid" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}agency-name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "agencyOrcid", "agencyName" })
@XmlRootElement(name = "funding-agency")
public class FundingAgency {

	@XmlElement(name = "agency-orcid")
	protected OrcidId agencyOrcid;
	@XmlElement(name = "agency-name")
	protected AgencyName agencyName;

	/**
	 * Gets the value of the agencyOrcid property.
	 * 
	 * @return possible object is {@link OrcidId }
	 * 
	 */
	public OrcidId getAgencyOrcid() {
		return agencyOrcid;
	}

	/**
	 * Sets the value of the agencyOrcid property.
	 * 
	 * @param value
	 *            allowed object is {@link OrcidId }
	 * 
	 */
	public void setAgencyOrcid(OrcidId value) {
		this.agencyOrcid = value;
	}

	/**
	 * Gets the value of the agencyName property.
	 * 
	 * @return possible object is {@link AgencyName }
	 * 
	 */
	public AgencyName getAgencyName() {
		return agencyName;
	}

	/**
	 * Sets the value of the agencyName property.
	 * 
	 * @param value
	 *            allowed object is {@link AgencyName }
	 * 
	 */
	public void setAgencyName(AgencyName value) {
		this.agencyName = value;
	}

}
