//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}security-details" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}preferences" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}scope"/>
 *       &lt;attGroup ref="{http://www.orcid.org/ns/orcid}visibility"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "securityDetails", "preferences" })
@XmlRootElement(name = "orcid-internal")
public class OrcidInternal {

	@XmlElement(name = "security-details")
	protected SecurityDetails securityDetails;
	protected Preferences preferences;
	@XmlAttribute
	protected Scope scope;
	@XmlAttribute
	protected Visibility visibility;

	/**
	 * Gets the value of the securityDetails property.
	 * 
	 * @return possible object is {@link SecurityDetails }
	 * 
	 */
	public SecurityDetails getSecurityDetails() {
		return securityDetails;
	}

	/**
	 * Sets the value of the securityDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link SecurityDetails }
	 * 
	 */
	public void setSecurityDetails(SecurityDetails value) {
		this.securityDetails = value;
	}

	/**
	 * Gets the value of the preferences property.
	 * 
	 * @return possible object is {@link Preferences }
	 * 
	 */
	public Preferences getPreferences() {
		return preferences;
	}

	/**
	 * Sets the value of the preferences property.
	 * 
	 * @param value
	 *            allowed object is {@link Preferences }
	 * 
	 */
	public void setPreferences(Preferences value) {
		this.preferences = value;
	}

	/**
	 * Gets the value of the scope property.
	 * 
	 * @return possible object is {@link Scope }
	 * 
	 */
	public Scope getScope() {
		return scope;
	}

	/**
	 * Sets the value of the scope property.
	 * 
	 * @param value
	 *            allowed object is {@link Scope }
	 * 
	 */
	public void setScope(Scope value) {
		this.scope = value;
	}

	/**
	 * Gets the value of the visibility property.
	 * 
	 * @return possible object is {@link Visibility }
	 * 
	 */
	public Visibility getVisibility() {
		return visibility;
	}

	/**
	 * Sets the value of the visibility property.
	 * 
	 * @param value
	 *            allowed object is {@link Visibility }
	 * 
	 */
	public void setVisibility(Visibility value) {
		this.visibility = value;
	}

}
