//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="given-names" type="{http://www.orcid.org/ns/orcid}non-empty-string"/>
 *         &lt;element name="family-name" type="{http://www.orcid.org/ns/orcid}non-empty-string" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}credit-name" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}other-names" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "givenNames", "familyName", "creditName", "otherNames" })
@XmlRootElement(name = "personal-details")
public class PersonalDetails {

	@XmlElement(name = "given-names", required = true)
	protected String givenNames;
	@XmlElement(name = "family-name")
	protected String familyName;
	@XmlElement(name = "credit-name")
	protected CreditName creditName;
	@XmlElement(name = "other-names")
	protected OtherNames otherNames;

	/**
	 * Gets the value of the givenNames property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGivenNames() {
		return givenNames;
	}

	/**
	 * Sets the value of the givenNames property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGivenNames(String value) {
		this.givenNames = value;
	}

	/**
	 * Gets the value of the familyName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFamilyName() {
		return familyName;
	}

	/**
	 * Sets the value of the familyName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFamilyName(String value) {
		this.familyName = value;
	}

	/**
	 * The full name of the researcher or contributor as it generally appears on
	 * their published works.
	 * 
	 * 
	 * @return possible object is {@link CreditName }
	 * 
	 */
	public CreditName getCreditName() {
		return creditName;
	}

	/**
	 * Sets the value of the creditName property.
	 * 
	 * @param value
	 *            allowed object is {@link CreditName }
	 * 
	 */
	public void setCreditName(CreditName value) {
		this.creditName = value;
	}

	/**
	 * (Optional) Container that includes other name(s) that the researcher or
	 * contributor may be known by.
	 * 
	 * 
	 * @return possible object is {@link OtherNames }
	 * 
	 */
	public OtherNames getOtherNames() {
		return otherNames;
	}

	/**
	 * Sets the value of the otherNames property.
	 * 
	 * @param value
	 *            allowed object is {@link OtherNames }
	 * 
	 */
	public void setOtherNames(OtherNames value) {
		this.otherNames = value;
	}

}
