//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-change-notifications"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}send-orcid-news"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}work-visibility-default"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sendChangeNotifications", "sendOrcidNews", "workVisibilityDefault" })
@XmlRootElement(name = "preferences")
public class Preferences {

	@XmlElement(name = "send-change-notifications", required = true)
	protected SendChangeNotifications sendChangeNotifications;
	@XmlElement(name = "send-orcid-news", required = true)
	protected SendOrcidNews sendOrcidNews;
	@XmlElement(name = "work-visibility-default", required = true)
	protected WorkVisibilityDefault workVisibilityDefault;

	/**
	 * Gets the value of the sendChangeNotifications property.
	 * 
	 * @return possible object is {@link SendChangeNotifications }
	 * 
	 */
	public SendChangeNotifications getSendChangeNotifications() {
		return sendChangeNotifications;
	}

	/**
	 * Sets the value of the sendChangeNotifications property.
	 * 
	 * @param value
	 *            allowed object is {@link SendChangeNotifications }
	 * 
	 */
	public void setSendChangeNotifications(SendChangeNotifications value) {
		this.sendChangeNotifications = value;
	}

	/**
	 * Gets the value of the sendOrcidNews property.
	 * 
	 * @return possible object is {@link SendOrcidNews }
	 * 
	 */
	public SendOrcidNews getSendOrcidNews() {
		return sendOrcidNews;
	}

	/**
	 * Sets the value of the sendOrcidNews property.
	 * 
	 * @param value
	 *            allowed object is {@link SendOrcidNews }
	 * 
	 */
	public void setSendOrcidNews(SendOrcidNews value) {
		this.sendOrcidNews = value;
	}

	/**
	 * Gets the value of the workVisibilityDefault property.
	 * 
	 * @return possible object is {@link WorkVisibilityDefault }
	 * 
	 */
	public WorkVisibilityDefault getWorkVisibilityDefault() {
		return workVisibilityDefault;
	}

	/**
	 * Sets the value of the workVisibilityDefault property.
	 * 
	 * @param value
	 *            allowed object is {@link WorkVisibilityDefault }
	 * 
	 */
	public void setWorkVisibilityDefault(WorkVisibilityDefault value) {
		this.workVisibilityDefault = value;
	}

}
