//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 12:59:45 PM GMT 
//

package uk.bl.odin.orcid.schema.messages.onepointone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source-orcid" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source-name" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}source-date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sourceOrcid", "sourceName", "sourceDate" })
@XmlRootElement(name = "source")
public class Source {

	@XmlElement(name = "source-orcid")
	protected OrcidId sourceOrcid;
	@XmlElement(name = "source-name")
	protected SourceName sourceName;
	@XmlElement(name = "source-date")
	protected SourceDate sourceDate;

	/**
	 * Gets the value of the sourceOrcid property.
	 * 
	 * @return possible object is {@link OrcidId }
	 * 
	 */
	public OrcidId getSourceOrcid() {
		return sourceOrcid;
	}

	/**
	 * Sets the value of the sourceOrcid property.
	 * 
	 * @param value
	 *            allowed object is {@link OrcidId }
	 * 
	 */
	public void setSourceOrcid(OrcidId value) {
		this.sourceOrcid = value;
	}

	/**
	 * Gets the value of the sourceName property.
	 * 
	 * @return possible object is {@link SourceName }
	 * 
	 */
	public SourceName getSourceName() {
		return sourceName;
	}

	/**
	 * Sets the value of the sourceName property.
	 * 
	 * @param value
	 *            allowed object is {@link SourceName }
	 * 
	 */
	public void setSourceName(SourceName value) {
		this.sourceName = value;
	}

	/**
	 * Gets the value of the sourceDate property.
	 * 
	 * @return possible object is {@link SourceDate }
	 * 
	 */
	public SourceDate getSourceDate() {
		return sourceDate;
	}

	/**
	 * Sets the value of the sourceDate property.
	 * 
	 * @param value
	 *            allowed object is {@link SourceDate }
	 * 
	 */
	public void setSourceDate(SourceDate value) {
		this.sourceDate = value;
	}

}
